namespace LiteGraph.Server.Classes
{
    using System.Collections.Generic;
    using LiteGraph;

    /// <summary>
    /// Request to onboard a tenant in a single operation.  Creates the tenant and, optionally, its initial users,
    /// credentials, and graphs.  Requires system-administrator authentication.  Onboarding is validated up front and
    /// fails fast: if any element is invalid or would conflict with an existing resource, nothing is created.
    /// </summary>
    public class TenantOnboardRequest
    {
        #region Public-Members

        /// <summary>
        /// Tenant to create.  Required.  When the GUID is omitted a new GUID is generated by the server; when supplied
        /// it must not collide with an existing tenant.
        /// </summary>
        public TenantMetadata Tenant { get; set; } = null;

        /// <summary>
        /// Users to create within the new tenant.  Optional.  Each user requires an email address and a password.
        /// Set <c>IsTenantAdmin</c> to grant a user administrative rights within the onboarded tenant.  The tenant GUID
        /// on each user is overwritten with the created tenant's GUID.
        /// </summary>
        public List<UserMaster> Users { get; set; } = new List<UserMaster>();

        /// <summary>
        /// Credentials (bearer tokens) to create within the new tenant.  Optional.  A bearer token that already exists
        /// causes the onboarding request to be rejected with a conflict.  When a credential has no user GUID and users
        /// were supplied, it is linked to the first created user.  The tenant GUID on each credential is overwritten
        /// with the created tenant's GUID.
        /// </summary>
        public List<Credential> Credentials { get; set; } = new List<Credential>();

        /// <summary>
        /// Graphs to create within the new tenant.  Optional.  The tenant GUID on each graph is overwritten with the
        /// created tenant's GUID.
        /// </summary>
        public List<Graph> Graphs { get; set; } = new List<Graph>();

        #endregion

        #region Private-Members

        #endregion

        #region Constructors-and-Factories

        /// <summary>
        /// Instantiate.
        /// </summary>
        public TenantOnboardRequest()
        {

        }

        #endregion

        #region Public-Methods

        #endregion

        #region Private-Methods

        #endregion
    }
}
