import { paths } from './constant';
import {
  HomeOutlined,
  ShareAltOutlined,
  ApartmentOutlined,
  BranchesOutlined,
  CrownOutlined,
  TeamOutlined,
  TagOutlined,
  TagsOutlined,
  RadarChartOutlined,
  LockOutlined,
  SaveOutlined,
  HistoryOutlined,
  ApiOutlined,
  SafetyCertificateOutlined,
} from '@ant-design/icons';
import { MenuItemProps } from '@/components/menu-item/types';

// Nav item `label`/`title` hold the English source strings (used as fallbacks
// and in unit tests); `labelKey`/`titleKey` reference the `nav.*` catalog and
// are what actually render, translated at runtime in MenuItems.
export const tenantDashboardRoutes: MenuItemProps[] = [
  {
    key: '/',
    icon: <HomeOutlined />,
    label: 'Home',
    title: 'Dashboard overview',
    labelKey: 'nav.tenant.home',
    titleKey: 'nav.tenant.homeTitle',
    path: paths.dashboardHome,
  },
  {
    key: '/graphs',
    icon: <ShareAltOutlined />,
    label: 'Graphs',
    title: 'Manage graph containers',
    labelKey: 'nav.tenant.graphs',
    titleKey: 'nav.tenant.graphsTitle',
    path: paths.graphs,
  },

  {
    key: '/nodes',
    icon: <ApartmentOutlined />,
    label: 'Nodes',
    title: 'Manage graph nodes',
    labelKey: 'nav.tenant.nodes',
    titleKey: 'nav.tenant.nodesTitle',
    path: paths.nodes,
  },
  {
    key: '/edges',
    icon: <BranchesOutlined />,
    label: 'Edges',
    title: 'Manage graph edges',
    labelKey: 'nav.tenant.edges',
    titleKey: 'nav.tenant.edgesTitle',
    path: paths.edges,
  },
  {
    key: '/labels',
    icon: <TagOutlined />,
    label: 'Labels',
    title: 'Manage classification labels',
    labelKey: 'nav.tenant.labels',
    titleKey: 'nav.tenant.labelsTitle',
    path: paths.labels,
  },
  {
    key: '/tags',
    icon: <TagsOutlined />,
    label: 'Tags',
    title: 'Manage key-value tags',
    labelKey: 'nav.tenant.tags',
    titleKey: 'nav.tenant.tagsTitle',
    path: paths.tags,
  },
  {
    key: '/vectors',
    icon: <RadarChartOutlined />,
    label: 'Vectors',
    title: 'Manage vector embeddings',
    labelKey: 'nav.tenant.vectors',
    titleKey: 'nav.tenant.vectorsTitle',
    path: paths.vectors,
  },
  {
    key: '/request-history',
    icon: <HistoryOutlined />,
    label: 'Requests',
    title: 'HTTP request history',
    labelKey: 'nav.tenant.requests',
    titleKey: 'nav.tenant.requestsTitle',
    path: paths.requestHistory,
  },
  {
    key: '/api-explorer',
    icon: <ApiOutlined />,
    label: 'API Explorer',
    title: 'Explore and invoke API endpoints',
    labelKey: 'nav.tenant.apiExplorer',
    titleKey: 'nav.tenant.apiExplorerTitle',
    path: paths.apiExplorer,
  },
];

export const adminDashboardRoutes: MenuItemProps[] = [
  {
    key: '/',
    icon: <CrownOutlined />,
    label: 'Tenants',
    title: 'Manage tenants',
    labelKey: 'nav.admin.tenants',
    titleKey: 'nav.admin.tenantsTitle',
    path: paths.adminDashboard,
  },
  {
    key: '/users',
    icon: <TeamOutlined />,
    label: 'Users',
    title: 'Manage user accounts',
    labelKey: 'nav.admin.users',
    titleKey: 'nav.admin.usersTitle',
    path: paths.users,
  },
  {
    key: '/credentials',
    icon: <LockOutlined />,
    label: 'Credentials',
    title: 'Manage API credentials',
    labelKey: 'nav.admin.credentials',
    titleKey: 'nav.admin.credentialsTitle',
    path: paths.credentials,
  },
  {
    key: '/authorization',
    icon: <SafetyCertificateOutlined />,
    label: 'Authorization',
    title: 'Manage roles and credential scopes',
    labelKey: 'nav.admin.authorization',
    titleKey: 'nav.admin.authorizationTitle',
    path: paths.authorization,
  },
  {
    key: '/backups',
    icon: <SaveOutlined />,
    label: 'Backups',
    title: 'Manage database backups',
    labelKey: 'nav.admin.backups',
    titleKey: 'nav.admin.backupsTitle',
    path: paths.backups,
  },
  {
    key: '/request-history',
    icon: <HistoryOutlined />,
    label: 'Requests',
    title: 'HTTP request history (all tenants)',
    labelKey: 'nav.admin.requests',
    titleKey: 'nav.admin.requestsTitle',
    path: paths.adminRequestHistory,
  },
  {
    key: '/api-explorer',
    icon: <ApiOutlined />,
    label: 'API Explorer',
    title: 'Explore and invoke API endpoints',
    labelKey: 'nav.admin.apiExplorer',
    titleKey: 'nav.admin.apiExplorerTitle',
    path: paths.adminApiExplorer,
  },
];
